services:
  cluster-master:
    image: firasj/spark-docker-cluster
    container_name: cluster-master
    ports:
      - "8088:8088"
      - "4040:4040"
      - "19888:19888"
      - "9000:9000"
      - "9870:9870"
    volumes:
      - "./app:/app"
    networks:
      - spark-cluster
    depends_on:
      - cluster-slave-1
      - cassandra-server
    hostname: cluster-master
    tty: true
    stdin_open: true
    working_dir: /app
    entrypoint:
      - bash
      - -c
      - "sed -i 's/\\r$//' /app/*.sh /app/mapreduce/*.py /app/*.py && bash /app/app.sh"
    
  cluster-slave-1:
    image: firasj/spark-docker-cluster
    container_name: cluster-slave-1
    networks:
      - spark-cluster
    hostname: cluster-slave-1
    tty: true

  cassandra-server:
    image: cassandra
    container_name: cassandra-server
    ports:
      - "9042:9042"
    networks:
      - spark-cluster
    environment:
      - CASSANDRA_CLUSTER_NAME=SearchEngineCluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe cluster' || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 20
      start_period: 60s


networks:
  spark-cluster:
    driver: bridge
